# coding: utf-8

"""
    Yodlee Core APIs

    This file describes the Yodlee Platform APIs, using the swagger notation. You can use this swagger file to generate client side SDKs to the Yodlee Platform APIs for many different programming languages. You can generate a client SDK for Python, Java, javascript, PHP or other languages according to your development needs. For more details about our APIs themselves, please refer to https://developer.yodlee.com/Yodlee_API/.  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: developer@yodlee.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import yodlee_client
from yodlee_client.models.asset_classification import AssetClassification  # noqa: E501
from yodlee_client.rest import ApiException


class TestAssetClassification(unittest.TestCase):
    """AssetClassification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssetClassification(self):
        """Test AssetClassification"""
        # FIXME: construct object with mandatory attributes with example values
        # model = yodlee_client.models.asset_classification.AssetClassification()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
