# coding: utf-8

"""
    Yodlee Core APIs

    This file describes the Yodlee Platform APIs using the swagger notation. You can use this swagger file to generate client side SDKs to the Yodlee Platform APIs for many different programming languages. Yodlee API v1.1 - Overview</a>.<br><br>You will have to set the header before making the API call. The following headers apply to all the APIs:<ul><li>Authorization: This header holds the access token</li> <li> Api-Version: 1.1</li></ul><b>Note</b>: If there are any API-specific headers, they are mentioned explicitly in the respective API's description.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: developer@yodlee.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import yodlee
from yodlee.models.classification_summary_account_summary import ClassificationSummaryAccountSummary  # noqa: E501
from yodlee.rest import ApiException

class TestClassificationSummaryAccountSummary(unittest.TestCase):
    """ClassificationSummaryAccountSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ClassificationSummaryAccountSummary
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = yodlee.models.classification_summary_account_summary.ClassificationSummaryAccountSummary()  # noqa: E501
        if include_optional :
            return ClassificationSummaryAccountSummary(
                account_id = 56, 
                last_updated = '', 
                site = '', 
                account_name = '', 
                account_type = '', 
                account_open_date = '', 
                transaction_summary = yodlee.models.classification_summary_transaction_summary.ClassificationSummaryTransactionSummary(
                    from_date = '', 
                    card_payments = True, 
                    is_primary_account = True, 
                    loan_payments = True, 
                    to_date = '', 
                    bill_payments = True, 
                    mortgage_payments = True, 
                    salary_credits = True, 
                    is_active_account = True, 
                    latest_transactions = [
                        yodlee.models.classification_summary_transaction.ClassificationSummaryTransaction(
                            date = '', 
                            amount = yodlee.models.money.Money(
                                amount = 1.337, 
                                converted_amount = 1.337, 
                                currency = 'USD', 
                                converted_currency = 'USD', ), 
                            description = yodlee.models.description.Description(
                                security = '', 
                                original = '', 
                                simple = '', 
                                consumer = '', ), 
                            merchant = yodlee.models.classification_summary_merchant.ClassificationSummaryMerchant(
                                name = '', ), 
                            base_type = 'CREDIT', )
                        ], 
                    income_credits = True, ), 
                available_balance = yodlee.models.money.Money(
                    amount = 1.337, 
                    converted_amount = 1.337, 
                    currency = 'USD', 
                    converted_currency = 'USD', )
            )
        else :
            return ClassificationSummaryAccountSummary(
        )

    def testClassificationSummaryAccountSummary(self):
        """Test ClassificationSummaryAccountSummary"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
