# coding: utf-8

"""
    Yodlee Core APIs

    This file describes the Yodlee Platform APIs using the swagger notation. You can use this swagger file to generate client side SDKs to the Yodlee Platform APIs for many different programming languages. Yodlee API v1.1 - Overview</a>.<br><br>You will have to set the header before making the API call. The following headers apply to all the APIs:<ul><li>Authorization: This header holds the access token</li> <li> Api-Version: 1.1</li></ul><b>Note</b>: If there are any API-specific headers, they are mentioned explicitly in the respective API's description.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: developer@yodlee.com
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from yodlee.configuration import Configuration


class UserDataTreatment(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'data_handling': 'DataHandling',
        'cdr_policy': 'CdrPolicy',
        'description': 'str'
    }

    attribute_map = {
        'data_handling': 'dataHandling',
        'cdr_policy': 'cdrPolicy',
        'description': 'description'
    }

    def __init__(self, data_handling=None, cdr_policy=None, description=None, local_vars_configuration=None):  # noqa: E501
        """UserDataTreatment - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._data_handling = None
        self._cdr_policy = None
        self._description = None
        self.discriminator = None

        self.data_handling = data_handling
        self.cdr_policy = cdr_policy
        self.description = description

    @property
    def data_handling(self):
        """Gets the data_handling of this UserDataTreatment.  # noqa: E501


        :return: The data_handling of this UserDataTreatment.  # noqa: E501
        :rtype: DataHandling
        """
        return self._data_handling

    @data_handling.setter
    def data_handling(self, data_handling):
        """Sets the data_handling of this UserDataTreatment.


        :param data_handling: The data_handling of this UserDataTreatment.  # noqa: E501
        :type data_handling: DataHandling
        """
        if self.local_vars_configuration.client_side_validation and data_handling is None:  # noqa: E501
            raise ValueError("Invalid value for `data_handling`, must not be `None`")  # noqa: E501

        self._data_handling = data_handling

    @property
    def cdr_policy(self):
        """Gets the cdr_policy of this UserDataTreatment.  # noqa: E501


        :return: The cdr_policy of this UserDataTreatment.  # noqa: E501
        :rtype: CdrPolicy
        """
        return self._cdr_policy

    @cdr_policy.setter
    def cdr_policy(self, cdr_policy):
        """Sets the cdr_policy of this UserDataTreatment.


        :param cdr_policy: The cdr_policy of this UserDataTreatment.  # noqa: E501
        :type cdr_policy: CdrPolicy
        """
        if self.local_vars_configuration.client_side_validation and cdr_policy is None:  # noqa: E501
            raise ValueError("Invalid value for `cdr_policy`, must not be `None`")  # noqa: E501

        self._cdr_policy = cdr_policy

    @property
    def description(self):
        """Gets the description of this UserDataTreatment.  # noqa: E501

        After we have finished using your data or you have withdraw your consent to use the data, it will be de-identified as per our  # noqa: E501

        :return: The description of this UserDataTreatment.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this UserDataTreatment.

        After we have finished using your data or you have withdraw your consent to use the data, it will be de-identified as per our  # noqa: E501

        :param description: The description of this UserDataTreatment.  # noqa: E501
        :type description: str
        """
        if self.local_vars_configuration.client_side_validation and description is None:  # noqa: E501
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserDataTreatment):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UserDataTreatment):
            return True

        return self.to_dict() != other.to_dict()
